### ISSUE TITLE
Now, is this bad?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#15]
It's the double icon, stupid!

![image](https://cloud.githubusercontent.com/assets/104830/20568299/52408bd8-b19c-11e6-8077-58e3c53abcbe.png)

And, yup, the title of this Issue is an example of **clickbait** :grinning:

**Comment by dennisschoenmakers** [comment]
I guess not.

**Comment by dennisschoenmakers** [comment]
> I guess not.

Not intended sarcastically. :smiley: I never heard any complaints about this.

**Comment by grdw** [comment]
> is an example of clickbait 

You never know what's going to happen next.
