### ISSUE TITLE
How can the fall of the oil price reduce CO2 emissions?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#17]
The slider does not impact CO2 at all:

![image](https://cloud.githubusercontent.com/assets/104830/20599218/47bd537e-b24d-11e6-8945-ceb8fb3334ed.png)

The console also says: `Slider costs_oil: -50`, so it is [**the same input**](https://github.com/quintel/etmobile/blob/3be541b1e79e2888a5a31384bdd5c09ceb193a2e/src/data/choices.js#L251).

**Comment by antw** [comment]
Apparently ETEngine wasn't resetting `balanced_values` if you *also* provided new inputs to be applied to the scenario.
