### ISSUE TITLE
Adding a timer

### ISSUE THREAD

**Issue by grdw** [quintel/etmobile#29]
I just installed it and ran it on my phone and just to add a little bit more adrenaline to the game it might be nice if each question must be solved within 30 seconds? I am not sure which time span would feel correct but we could test that out. It takes me about 20 seconds to read the text and than another 10 to make a choice.

Visually it would be cool if the timer works like the youtube loading bar:

![screen shot 2016-11-28 at 17 24 26](https://cloud.githubusercontent.com/assets/2676542/20676288/8937ad50-b58f-11e6-8b81-92edc1b2b491.png)

**Comment by dennisschoenmakers** [comment]
Great idea! We already have a (currently unused) [**ProgressBar**](https://github.com/quintel/etmobile/blob/5b450a1fe5b2f064098ee145696fd22a2751a3e4/src/components/ProgressBar.js) we could re-use.
