### ISSUE TITLE
It should be easier to see how many correct answers you have

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmobile#50]
Now the number swooshes by quite fast and in a modest shade of grey and does not get registered easily (by me at least).

Additionally, perhaps it would be nice to keep the score visible in a top corner or something.

**Comment by antw** [comment]
Thanks for the suggestion. You're right that hiding it at the bottom of the page isn't ideal; it was meant to be temporary but managed to endure. 😆 

I'm going to rethink the header so that we can show the score there along with the number of remaining tries at lower difficulty settings (#51).
