### ISSUE TITLE
cheaperOil is a very misleading option IMO

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmobile#57]
"The price of oil is tracked by many and discussed on a daily basis in the news. Does it have an impact of the CO<sub>2</sub> emissions of our energy system?"

Stated like this, the answer should of course be "YES!". There is all kinds of impact to be expected ranging from manufacturing to transport and electricity production. The ETM only treats the latter (with the Merit module) which is quite a subtle effect (depending on the differences between the oil-price and the prices of other fuels etc.)

Perhaps we should remove this as I cannot think of a better phrasing that will make this a more fun option.

**Comment by dennisschoenmakers** [comment]
The intension was to add a bit of a gimmick, but thinking about it again, it probably leads to a more confusion. Let us remove it.

**Comment by AlexanderWirtz** [comment]
Whatever the intention was: let's get rid of it

**Comment by dennisschoenmakers** [comment]
Gone.
