### ISSUE TITLE
How to maintain correctness of choices

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmobile#63]
Choices currently result in setting a slider to an absolute value. Closing a coal power plant is done by setting the slider to a value of 1.0 less than the current default. For example:

* Current value: 1.3 units
* Slider-setting related to choice of closing a power plant: 0.3 units

However, if we change the defaults (with a new dataset), the slider-setting of 0.3 may no longer correspond to closing one unit. 

Would it be difficult to make this more robust by reading out the current (start-year) value and subtract 1.0 from that?

**Comment by dennisschoenmakers** [comment]
Double of #8. 

@antw and I discussed that we need to keep an eye out on this (and also e.g. the CO2 calculated numbers) when we do a deployment.
