### ISSUE TITLE
Missing translation after finishing

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#74]
When you've finished in Dutch:

![image](https://cloud.githubusercontent.com/assets/104830/22830947/b4deea42-efa8-11e6-9f26-00f8b292b2b1.png)

This does not happen in English:

![image](https://cloud.githubusercontent.com/assets/104830/22830989/ea99a56e-efa8-11e6-8730-ba5bf2b842a2.png)

**Comment by antw** [comment]
[The translation is incorrectly formatted](https://github.com/quintel/etmobile/blob/b0fc8d76415b46669d7c1c88082902f2e0fc51d1/src/data/locales/nl/summary.js#L5-L11).

```js
{
  numberCorrect: `
    Je had {correct, plural,
      =0 {no correct choices!}
      één {one correct choice.}
      ander {{correct} correct choices.}
    }
}
```

... it should be ...

```js
{
  numberCorrect: `
    You made {correct, plural,
      =0 {no correct choices!}
          ^^^^^^^^^^^^^^^^^^^ Translate this
          
      one {one correct choice.}
           ^^^^^^^^^^^^^^^^^^^ Translate this
           
      other {{correct} correct choices.}
                       ^^^^^^^^^^^^^^^^ Translate this
                                            
    }
  `
}
```

The text to be translated is inside the `{ ... }` brackets; `=0`, `one` and `other` tell the translation library which text to show depending on the number of correct choices (zero, one, and any other number of correct choices).

Think of it like this:

```ruby
translation = 'You made '

if correct_choices.zero?
  translation += 'no correct choices!'
elsif correct_choices == 1
  translation += 'one correct choice.'
else
  translation += "#{correct_choices} correct choices."
end

**Comment by antw** [comment]
> dennisschoenmakers assigned antw and unassigned dennisschoenmakers

I can't do much with this myself. 😆 But if you could translate the following three messages I can update the translations for you.

* You made no correct choices
* You made one correct choice
* You made 5 correct choices
