### ISSUE TITLE
Explain why this option does this and that

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#78]
So we can help explain e.g. why some options are much better or worse than others. 

@antw: can you pinpoint @AlexanderWirtz to the place where he can add/edit these 'explanations'?

**Comment by antw** [comment]
Explanation texts for each choice may be added in the following files:

* [src/data/locales/en/choices.js](https://github.com/quintel/etmobile/blob/master/src/data/locales/en/choices.js)
* [src/data/locales/nl/choices.js](https://github.com/quintel/etmobile/blob/master/src/data/locales/nl/choices.js)

You may add an optional `why` attribute underneath the `description` for each choice; this will be shown on the summary page (once the game has ended) to explain why the choice has the effect that it does. If no `why` is added, the app will fallback to using the `description` instead.

For example:

#### Before:

```js
  closeConventionalCoal: {
    name: 'Close a conventional coal power plant',
    description: `
      You can close a conventional 800 megawatt (MWe) coal-fired plant. These plants 
      are not build anymore in rich countries due to environmental restrictions.
    `
  }
```

#### After:

```js
  closeConventionalCoal: {
    name: 'Close a conventional coal power plant',
    description: `
      You can close a conventional 800 megawatt (MWe) coal-fired plant. These plants 
      are not build anymore in rich countries due to environmental restrictions.
    `,
    why: `
      Coal is made primarily of carbon. Burning coal in power plants releases almost all
      of this carbon directly into the atmosphere. Closing a coal power plant therefore
      removes this source of carbon, but it will have to be replaced with a cleaner
      alternative, such as wind, solar, or nuclear.
    `
  }

**Comment by dennisschoenmakers** [comment]
Thanks! +1 for the `why`! :smiley:
