### ISSUE TITLE
Site does not load on Android 6

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#92]
Tested on Samsung Galaxy S7, through Browserstack, using the (standard) Internet app:

![image](https://user-images.githubusercontent.com/104830/27589647-6fd578ca-5b4c-11e7-8047-0474b1ea9210.png)

Reported through @AlexanderWirtz

**Comment by antw** [comment]
@dennisschoenmakers We don't have a Browserstack account, do we? Did you use the free trial?
