### ISSUE TITLE
When the user has selected a choice, he should see a pop up with explanation why

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#93]
Currently, when you have selected a choice, you'll continue to the next question. This was a conscious choice, but our client rather sees another solution now.

When you select a choice ('right' or 'wrong', we don't care), you should get a pop-up with the explanation texts, that you have to dismiss.

cc @ChaelKruip

**Comment by ChaelKruip** [comment]
I think this is bad idea for two reasons:
1. Pop-ups are annoying as hell
2. If you want to play a game, the element of flow and speed are important. If we even want people to battle each other using the game, pop-ups will make that impossible

**Comment by dennisschoenmakers** [comment]
Could we make it a setting whether or not users want to receive direct feedback after every choice?

**Comment by antw** [comment]
> If you want to play a game, the element of flow and speed are important. If we even want people to battle each other using the game, pop-ups will make that impossible

This was my first thought too; it disrupts the flow of the game by injecting an extra screen between questions.

However if we must do it, I suggest we slide the question out of view (as we do today) and instead of showing the next question, show the explanation as to why their answer was incorrect. Pressing a button would then forward the visitor to the next question.

**Comment by ChaelKruip** [comment]
> Pressing a button would then forward the visitor to the next question.

Wouldn't swiping be more natural?

**Comment by dennisschoenmakers** [comment]
> However if we must do it, I suggest we slide the question out of view (as we do today) and instead of showing the next question, show the explanation as to why their answer was incorrect. Pressing a button would then forward the visitor to the next question.

Could you make a quick implementation of it?

**Comment by ChaelKruip** [comment]
> Could you make a quick implementation of it?

I'd like to know how quick before we sacrifice valuable heat pump time 😬

**Comment by dennisschoenmakers** [comment]
> Could you make a quick implementation of it?

How much time would this take you think? Then @ChaelKruip can put this in his planning?

**Comment by antw** [comment]
> Wouldn't swiping be more natural?

I'd agree with you if the app made heavier use of swiping gestures, but it would be unintuitive to support swiping on just this one page.

> I'd like to know how quick

In my experience with ETMobile to date, I would suggest ~1 day to add a new page like this. It might be less, but I'm playing it safe. 😆

We need to account for tests – new, and changes to existing – and possible new translations. One day was how long it took to add the "previous question summary" thingy in May, and the "result page explanation texts" in March.

**Comment by ChaelKruip** [comment]
> In my experience with ETMobile to date, I would suggest ~1 day to add a new page like this.

I say we look at it after the heat pump project.

**Comment by dennisschoenmakers** [comment]
Discussed with the client that an explanation should be provided after *every* choice, so including 'correct' choices. Updated the description above.
